sed -i 's/eius/ejus/g' *
sed -i 's/Ier/Jer/g' *
sed -i 's/Iesu/Jesu/g' *
sed -i 's/Ioseph/Joseph/g' *
sed -i 's/llelúia/llelúja/g' *
sed -i 's/Iud/Jud/g' *
sed -i 's/Ioánn/Joánn/g' *
sed -i 's/uius/ujus/g' *
sed -i 's/iug/jug/g' *
sed -i 's/Iacob/Jacob/g' *
sed -i 's/iuxta/juxta/g' *
sed -i 's/iam/jam/g' *
sed -i 's/bjam/biam/g' *
sed -i 's/cjam/ciam/g' *
sed -i 's/djam/diam/g' *
sed -i 's/ljam/liam/g' *
sed -i 's/mjam/miam/g' *
sed -i 's/njam/niam/g' *
sed -i 's/pjam/piam/g' *
sed -i 's/sjam/siam/g' *
sed -i 's/rjam/riam/g' *
sed -i 's/tjam/tiam/g' *
sed -i 's/iniúri/injúri/g' *
sed -i 's/iubil/jubil/g' *
sed -i 's/Iubil/Jubil/g' *
sed -i 's/iuv/juv/g' *
sed -i 's/Iuv/Juv/g' *
sed -i 's/iura/jura/g' *
sed -i 's/iure/jure/g' *
sed -i 's/ius/jus/g' *
sed -i 's/njus/nius/g' *
sed -i 's/ljus/lius/g' *
sed -i 's/rjus/rius/g' *
sed -i 's/sjus/sius/g' *
sed -i 's/tjus/tius/g' *
sed -i 's/iucúnd/jucúnd/g' *
sed -i 's/iud/jud/g' *
sed -i 's/iact/jact/g' *
sed -i 's/iácul/jácul/g' *
sed -i 's/iec/jec/g' *
